### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by code-by** [jxnblk/repng#13]
After installing (yarn global add repng) I got this

ERROR in ./\~/datauri/index.js
Module parse failed: /react-app/node_modules/babel-loader/lib/index.js??ref--0!/react-app/node_modules/datauri/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| 'use strict';
| var semver=require('semver');
 @ ./~/repng/index.js 6:12-30

node v7.9.0
npm  v4.2.0
react v.15.4
react-native-web v.0.0.94

**Comment by fufjvnvnf** [comment]
same here; can't use in webpack

**Comment by PAK90** [comment]
I got this too; any chance of a resolution?
