### ISSUE TITLE
Rendering Chinese text is producing junk

### ISSUE THREAD

**Issue by han4wluc** [jxnblk/repng#14]
I dont know if this is a encoding problem or font problem.

`       <div className="sub-1">
              {'你好'}
            </div>`

`repng Subtitles.js`

It is produces this image
![subtitles js-2017-11-13-12-25-49-1024x768](https://user-images.githubusercontent.com/8134740/32709758-e5b865f0-c86d-11e7-97e3-712ed2a6802f.png)

**Comment by jxnblk** [comment]
Sorry for the delay -- not sure what the issue was, but it looks like it should work now
