### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by esetnik** [jxnblk/repng#17]
Can you include support for babel 7?

**Comment by mattyao-cotd** [comment]
Please update to Babel 7.

**Comment by jxnblk** [comment]
Now that it's out of beta, I'd accept a PR for babel 7

**Comment by svenvanlierde** [comment]
Is it possible to update to Babel7 ? thanks !

**Comment by jxnblk** [comment]
v4 now uses Babel 7
