### ISSUE TITLE
Out of the box SSR rendering

### ISSUE THREAD

**Issue by degroote22** [jxnblk/repng#2]
Please excuse me if the words I'm using aren't correct but as soon as I saw this I imagined some great use that could be better out of the box.
Imagine you have something like a scoreboard and would like to embed this on other sites.
You'd use iframes or something but instead I could wire this with an http endpoint and stream the png back so that the user uses my link on the src="" of an image and it works.
I believe the core functionality for this already exists but it's just not clear and easy as it could be.

Thanks for your time and great work @jxnblk and please excuse me if I said something wrong

**Comment by jxnblk** [comment]
I forgot to merge the branch in earlier, but you can use this as a node module, have a look at https://github.com/jxnblk/repng/blob/master/index.js since there aren't any real docs for this yet.

You could probably roll your own custom module too using https://github.com/sindresorhus/pageres
