### ISSUE TITLE
Add repng to my project causes failed to compile

### ISSUE THREAD

**Issue by johnlim5847** [jxnblk/repng#27]
This is the error I got when I try to call it in my app by following the example

```
./node_modules/puppeteer/lib/Launcher.js
Module not found: Can't resolve 'child_process' in '/Users/NAME/Desktop/PROJECT/node_modules/puppeteer/lib'
```

**Comment by jxnblk** [comment]
What do you mean by "app"? This should work as a Node.js module, but you'll need to run in an environment where Puppeteer works

**Comment by johnlim5847** [comment]
@jxnblk I'm so sorry I thought it was a npm package that can be run in my react app my bad!

**Comment by jxnblk** [comment]
No worries! Maybe the docs need to be a little clearer around the usage as a module – you *should,* in theory, be able to set it up in a microservice that a browser-based app can make requests to if that's helpful at all
