### ISSUE TITLE
Rendering Empty Files .png

### ISSUE THREAD

**Issue by jppgomes** [jxnblk/repng#33]
repng "./lead.js" -f bot_template.png --width 512 --height 780 --css ./App.css --out-dir ./

Rendering Ok, but the file is empty? any solution ? Thanksss

**Comment by johnletey** [comment]
@jxnblk I'm also experiencing this

**Comment by kvicrey-ls** [comment]
Same here!

**Comment by johnletey** [comment]
@kvicrey-ls this is extremely weird

**Comment by kvicrey-ls** [comment]
Yes, I'm debugging right now. Puppeter creates the screenshot just fine. It might be something wrong with writing the stream to a file.
I'll let you know.

**Comment by jppgomes** [comment]
Hello Guys, I was able to find out the problem, repng currently works only with the version of node 8.X

**Comment by johnletey** [comment]
@jppgomes It sure does ... just tried with `8.0.0` and it works fine

**Comment by kvicrey-ls** [comment]
Rhh ok, I'll try to fix it for node 8+ and open a PR.
Thanks @jppgomes !

**Comment by Anomen** [comment]
If anyone of you could try the fix, that would be much appreciated: https://github.com/jxnblk/repng/pull/34 :)

Thanks!

**Comment by jxnblk** [comment]
Should be fixed in `3.2.0` but feel free to open another issue if not

**Comment by johnletey** [comment]
@jxnblk Thank you Brent!
