### ISSUE TITLE
Customize Puppeteer option

### ISSUE THREAD

**Issue by SindreSvendby** [jxnblk/repng#35]
Great project.

I needed to customize some of the Puppeteer options to be able to use this on Heroku.
I created a fork where I can pass in puppeteer options.

instead of keeping a fork of your project, would you accept a PR to include the changes in your repo?

**Comment by TreTuna** [comment]
This would help out those of us trying to use repng inside of Docker containers as well! Something I'm currently battling with.

**Comment by jxnblk** [comment]
Thanks for the work on this @SindreSvendby -- the next major version will support passing options through
